name: "Lint and test"

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-test:
    name: Lint-and-test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install system dependencies(libssl-dev)
        run: |
          sudo apt-get install libssl-dev

      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
